### ISSUE TITLE
How to use it with FastAPI?

### ISSUE THREAD

**Issue by elieobeid7** [siddhantgoel/streaming-form-data#101]
I have this

```
async def foo(
    request: Request,
    file: UploadFile = File(...))
    ...
```

how to transition to using this library. Currently, the upload of 47mb file takes about 10min, you can read more [here](https://stackoverflow.com/questions/78320199/how-to-improve-nginx-uvicorn-upload-speed)

Is this library really that fast? I expect the file to be uploaded in a maximum of 30s, if this library would just improve the upload speed by a few seconds then I won't bother using it.

**Comment by elieobeid7** [comment]
yes I have tried using `request.stream` and I keep getting [Stream consumed](https://github.com/getsentry/sentry-python/issues/1675) error, no matter what I do.

I'm using HTMX on the frotnend and I'm forced to use form data because that's how HTMX [handles uploads](https://htmx.org/examples/file-upload/) as far as I know. It's my first project using HTMX on the frontend.

**Comment by siddhantgoel** [comment]
Form data is the right encoding to use.

You could try to put a breakpoint right before the "stream consumed" error is raised to figure out who is raising it? My guess is that since you have `UploadFile` as a dependency, that might be the reason (because `File` would read the request body to keep some of it in memory and spool the rest to disk, so by the time you call `request.stream` the request body has already been read).

Another thing to try is to modify the function signature to `async def foo(request: Request)` and then use `request.stream`.

**Comment by elieobeid7** [comment]
I fixed the issue by adding those two lines to nginx

``` 
Header set Accept-Ranges bytes; // inside the server block
proxy_force_ranges on;  # inside the location block.
```
 I wasn't trying to fix the upload issue, I was trying to fix [videojs currentTime issue on Chrome only](https://stackoverflow.com/questions/22728016/nginx-is-not-accepting-range-of-bytes).
