### ISSUE TITLE
Any ideas how to deal with excel files in streaming ?

### ISSUE THREAD

**Issue by MohamedLEGH** [siddhantgoel/streaming-form-data#45]
Hello,
Thanks for your work.
I can read and parse csv file with your library in streaming.
I want to do the same with excel file but I didn't find a way to do it.
I know it's not directly related to your library but maybe you have a clue.
Is it possible to convert a excel file to a csv file reading a http stream ? or is it possible to read a excel file directly from the stream ?

**Comment by siddhantgoel** [comment]
Hey, excel files can take up a bunch of different forms. From the [Wikipedia page](https://en.wikipedia.org/wiki/Microsoft_Excel#File_formats), it looks like it's possible for an Excel file to contain binary data, XML data, or even a zip archive containing a bunch of different XML files. Given the wide variety, I'm not sure if reading such formats directly from the stream is easy (or even doable). CSV is a much simpler format because each line is self-contained.
