### ISSUE TITLE
smart-open as an optional dependency

### ISSUE THREAD

**Issue by wlhlm** [siddhantgoel/streaming-form-data#81]
I'm packaging streaming-form-data in the [AUR](https://aur.archlinux.org/packages/python-streaming-form-data/). Since 1.12.0, this package depends in smart-open, which unfortunately pulls in boto3, a pretty heavyweight library. Previously, streaming-form-data was very light on dependencies. Would it be possible to make this new dependency optional? Thanks for your work on this library!

**Comment by siddhantgoel** [comment]
I wonder why that's happening because the dependency is currently set to `smart-open>=6.0` ([here](https://github.com/siddhantgoel/streaming-form-data/blob/main/setup.py#L47)) which should not install anything other than plain smart-open. For smart-open to install boto3, the dependency should have been set to `smart-open[s3]>=6.0` because smart-open also supports optional dependencies. 🤔

**Comment by wlhlm** [comment]
Oh, I see now. I wasn't aware that it's optional for `smart-open`. The problem then is on the Arch Linux side where the [`python-smart_open`](https://aur.archlinux.org/packages/python-smart_open) packager decided to make `boto3` a required dependency. I'll go ask them to consider changing that. It's not a problem on your side. Thank you for the quick response! 👍

**Comment by siddhantgoel** [comment]
Sure, no worries!
