### ISSUE TITLE
Question: Is it possible to raise an error when data for a non-registered target is parsed?

### ISSUE THREAD

**Issue by hbusul** [siddhantgoel/streaming-form-data#87]
Hi first of all thanks for this great library. I'm experimenting with it  and it makes a huge difference for us in upload speeds. 
Maybe I missed it in documentation but is it possible to raise an exception when data for a non-registered target
is parsed? I assume right now that data is discarded. But I would like to raise an exception, you know maybe
you were writing a client library and typed a field name incorrectly, if this goes silently, user might
fail to see the field name was incorrect etc.

**Comment by siddhantgoel** [comment]
At the moment the parser passes everything unknown to a `NullTarget()` so it should definitely be possible to raise an error instead. I have the feeling though that raising an error has the potential to break existing code.

There could be the case where a form contains 5 fields and on the backend we only care about the performance for 4 fields and the fifth field is outside the scope of this library. Maybe a [`warnings.warn()`](https://docs.python.org/3/library/warnings.html#warnings.warn) call would be a lightweight alternative of achieving a similar thing?

**Comment by siddhantgoel** [comment]
I do like the idea of a `strict` mode. Would you be up for opening a PR? I think there are very few function signatures we'd need to adjust, and then update the documentation.

**Comment by hbusul** [comment]
Sure, then I'll try to implement it.  I always wanted to test Cython as long as you review why not :D

**Comment by siddhantgoel** [comment]
Awesome! 🎉 

Just something to get you started with: the `streaming_form_data.parser.Parser` class is the Python entry-point while the `_Parser` class is the one running in Cython space. There's a `streaming_form_data._parser._Parser._part_for` method that is called to get the current `Part` (basically the current chunk of input being uploaded) while the parsing is being done to feed it some bytes. Inside the parsing loop there's a `part = self._part_for(name) or self.default_part` check so that's probably where you would need to return an error.

Let me know if there's anything I can help with and looking forward to seeing that PR!

**Comment by hbusul** [comment]
Thanks a lot, I will look into those!

**Comment by hbusul** [comment]
@siddhantgoel thanks for reviewing and merging the changes! Now that it is merged, I'm closing the issue.
